### PR TITLE
Add ADR-0001

### PR DESCRIPTION
**Pull request by pkalita-lbl**
Adding ADR-0001 summarizing recent decisions around improving linkage between the home page / landing site and other NMDC products.

### CODE REVIEW

**Review by ssarrafan — COMMENTED** [review]
Thanks @pkalita-lbl for putting this together.  I think sharing this with the larger team at next Wednesday's sync would be a good next step. The issue I think that requires further discussion is around the headless CMS.  Would you agree the transition to the CMS would be beyond MVP?

**Comment by shreddd** [comment]
This looks good to me.

**Comment by shreddd** [comment]
@ssarrafan - I think this is saying we won't do the headless so I think that is OK. It is just the other alternative that we decided not to do.

**Comment by pkalita-lbl** [comment]
Yes, Shreyas' interpretation is right. The headless CMS thing was an option that was considered but that was decided against -- i.e. no need to pursue it further right now. I tried to follow the ARD template as closely as possible, but maybe it doesn't make that totally clear. I'm happy to talk about this at next Wednesday's sync.

**Pull request merged**
